### ISSUE TITLE
Icon display when not available

### ISSUE THREAD

**Issue by Romero-KCBS2003** [home-assistant-community-themes/blue-night#37]
I noticed that for entities they are currently unavailable or unknown, the icons are displayed faded bright and for entities they are worked normally and are available, the icons are displayed faded.
Shouldn't this be the other way around?
BR
![SmartSelect_20230921_071056_Home Assistant](https://github.com/home-assistant-community-themes/blue-night/assets/135272332/c44940f0-c217-427d-b889-4cb0f8bfcb54)

**Comment by sdrapha** [comment]
I would keep the grey shade of the icons though. since changing that would be a massive change to the whole interface which is not welcome.
The real issue here, which I agree, is the unavailable entities, they should have the same shade of gray as the normal icons, and not be brighter. If they were to be different, even more faded then. but probably the best would be just the same color. to have a consistent look in the gui.

**Comment by Romero-KCBS2003** [comment]
> I would keep the grey shade of the icons though. since changing that would be a massive change to the whole interface which is not welcome. The real issue here, which I agree, is the unavailable entities, they should have the same shade of gray as the normal icons, and not be brighter. If they were to be different, even more faded then. but probably the best would be just the same color. to have a consistent look in the gui.

Okay. And do you know how to set in the theme that the icons are always the same shade, especially when they are not available?
I'm not familiar with the theme yaml files unfortunately.
BR

**Comment by sdrapha** [comment]
I think I know how to fix that, give me some time and I test the implementation locally and then make a PR.
